apiVersion: v2
name: helmet
description: Helmet is a library Helm Chart for grouping common logics. This chart is not deployable by itself.
home: https://github.com/auto-dj/helmet/blob/main/charts/helmet
type: library
version: "0.11.0"
appVersion: "0.11.0"
keywords:
  - common
  - helper
  - template
  - function
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
    - bitnami-common
    version: 2.x.x
