apiVersion: v1
entries:
  common:
  - annotations:
      category: Infrastructure
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 2.19.0
    created: "2024-03-14T00:09:45.416728+01:00"
    description: A Library Helm Chart for grouping common logic between bitnami charts.
      This chart is not deployable by itself.
    digest: 89e4008ba84ebc4b1838b7266bd991958f57eedb841e9268726de971dc78cfd1
    home: https://bitnami.com
    icon: https://bitnami.com/downloads/logos/bitnami-mark.png
    keywords:
    - common
    - helper
    - template
    - function
    - bitnami
    maintainers:
    - name: VMware, Inc.
      url: https://github.com/bitnami/charts
    name: common
    sources:
    - https://github.com/bitnami/charts
    type: library
    urls:
    - charts/common-2.19.0.tgz
    version: 2.19.0
generated: "2024-03-14T00:09:45.415457+01:00"
